shared: &shared
  aws_s3_access_key_id: <%= ENV["AWS_S3_ACCESS_KEY_ID"] %>
  aws_s3_secret_access_key: <%= ENV["AWS_S3_SECRET_ACCESS_KEY"] %>
  aws_s3_bucket_name: <%= ENV["AWS_S3_BUCKET_NAME"] %>
  jwt_encryption_key: <%= ENV["JWT_ENCRYPTION_KEY"] %>
  jwt_signing_key: <%= ENV["JWT_SIGNING_KEY"] %>

development:
  <<: *shared

test:
  <<: *shared

production:
  <<: *shared
