on:
  push:
    branches:
      - master

name: Run specs

jobs:
  specs:
    name: Setup and run specs
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:12-2.5
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: every_mans_land_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
      - name: Install Bundler
        run: gem install bundler:2.1.4
      - name: Gem caching
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Run specs
        run: bundle exec rake spec
        env:
          RAILS_ENV: test
          SECRET_KEY_BASE: deadbeef
